
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Cat': typeof import("../components/Cat.vue")['default']
    'CatSingleAdmin': typeof import("../components/CatSingleAdmin.vue")['default']
    'CatSingleOpen': typeof import("../components/CatSingleOpen.vue")['default']
    'CatsAdmin': typeof import("../components/CatsAdmin.vue")['default']
    'CatsOpen': typeof import("../components/CatsOpen.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'MobileHeader': typeof import("../components/MobileHeader.vue")['default']
    'Nav': typeof import("../components/Nav.vue")['default']
    'Pagination': typeof import("../components/Pagination.vue")['default']
    'Prod': typeof import("../components/Prod.vue")['default']
    'ProdAdminSingle': typeof import("../components/ProdAdminSingle.vue")['default']
    'ProdSingleOpen': typeof import("../components/ProdSingleOpen.vue")['default']
    'ProdsAdmin': typeof import("../components/ProdsAdmin.vue")['default']
    'Prodsearch': typeof import("../components/Prodsearch.vue")['default']
    'Prodsopen': typeof import("../components/Prodsopen.vue")['default']
    'Searchbar': typeof import("../components/Searchbar.vue")['default']
    'Sidebar': typeof import("../components/Sidebar.vue")['default']
    'SubCatSingleAdmin': typeof import("../components/SubCatSingleAdmin.vue")['default']
    'SubCatSingleOpen': typeof import("../components/SubCatSingleOpen.vue")['default']
    'Subcat': typeof import("../components/Subcat.vue")['default']
    'SubcatsAdmin': typeof import("../components/SubcatsAdmin.vue")['default']
    'SubcatsOpen': typeof import("../components/SubcatsOpen.vue")['default']
    'Tagg': typeof import("../components/Tagg.vue")['default']
    'TiptapEditor': typeof import("../components/TiptapEditor.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'TiptapEditorContent': typeof import("../node_modules/@tiptap/vue-3/dist/index")['EditorContent']
    'TiptapFloatingMenu': typeof import("../node_modules/@tiptap/vue-3/dist/index")['FloatingMenu']
    'TiptapBubbleMenu': typeof import("../node_modules/@tiptap/vue-3/dist/index")['BubbleMenu']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCat': typeof import("../components/Cat.vue")['default']
    'LazyCatSingleAdmin': typeof import("../components/CatSingleAdmin.vue")['default']
    'LazyCatSingleOpen': typeof import("../components/CatSingleOpen.vue")['default']
    'LazyCatsAdmin': typeof import("../components/CatsAdmin.vue")['default']
    'LazyCatsOpen': typeof import("../components/CatsOpen.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyMobileHeader': typeof import("../components/MobileHeader.vue")['default']
    'LazyNav': typeof import("../components/Nav.vue")['default']
    'LazyPagination': typeof import("../components/Pagination.vue")['default']
    'LazyProd': typeof import("../components/Prod.vue")['default']
    'LazyProdAdminSingle': typeof import("../components/ProdAdminSingle.vue")['default']
    'LazyProdSingleOpen': typeof import("../components/ProdSingleOpen.vue")['default']
    'LazyProdsAdmin': typeof import("../components/ProdsAdmin.vue")['default']
    'LazyProdsearch': typeof import("../components/Prodsearch.vue")['default']
    'LazyProdsopen': typeof import("../components/Prodsopen.vue")['default']
    'LazySearchbar': typeof import("../components/Searchbar.vue")['default']
    'LazySidebar': typeof import("../components/Sidebar.vue")['default']
    'LazySubCatSingleAdmin': typeof import("../components/SubCatSingleAdmin.vue")['default']
    'LazySubCatSingleOpen': typeof import("../components/SubCatSingleOpen.vue")['default']
    'LazySubcat': typeof import("../components/Subcat.vue")['default']
    'LazySubcatsAdmin': typeof import("../components/SubcatsAdmin.vue")['default']
    'LazySubcatsOpen': typeof import("../components/SubcatsOpen.vue")['default']
    'LazyTagg': typeof import("../components/Tagg.vue")['default']
    'LazyTiptapEditor': typeof import("../components/TiptapEditor.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyTiptapEditorContent': typeof import("../node_modules/@tiptap/vue-3/dist/index")['EditorContent']
    'LazyTiptapFloatingMenu': typeof import("../node_modules/@tiptap/vue-3/dist/index")['FloatingMenu']
    'LazyTiptapBubbleMenu': typeof import("../node_modules/@tiptap/vue-3/dist/index")['BubbleMenu']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Cat: typeof import("../components/Cat.vue")['default']
export const CatSingleAdmin: typeof import("../components/CatSingleAdmin.vue")['default']
export const CatSingleOpen: typeof import("../components/CatSingleOpen.vue")['default']
export const CatsAdmin: typeof import("../components/CatsAdmin.vue")['default']
export const CatsOpen: typeof import("../components/CatsOpen.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const MobileHeader: typeof import("../components/MobileHeader.vue")['default']
export const Nav: typeof import("../components/Nav.vue")['default']
export const Pagination: typeof import("../components/Pagination.vue")['default']
export const Prod: typeof import("../components/Prod.vue")['default']
export const ProdAdminSingle: typeof import("../components/ProdAdminSingle.vue")['default']
export const ProdSingleOpen: typeof import("../components/ProdSingleOpen.vue")['default']
export const ProdsAdmin: typeof import("../components/ProdsAdmin.vue")['default']
export const Prodsearch: typeof import("../components/Prodsearch.vue")['default']
export const Prodsopen: typeof import("../components/Prodsopen.vue")['default']
export const Searchbar: typeof import("../components/Searchbar.vue")['default']
export const Sidebar: typeof import("../components/Sidebar.vue")['default']
export const SubCatSingleAdmin: typeof import("../components/SubCatSingleAdmin.vue")['default']
export const SubCatSingleOpen: typeof import("../components/SubCatSingleOpen.vue")['default']
export const Subcat: typeof import("../components/Subcat.vue")['default']
export const SubcatsAdmin: typeof import("../components/SubcatsAdmin.vue")['default']
export const SubcatsOpen: typeof import("../components/SubcatsOpen.vue")['default']
export const Tagg: typeof import("../components/Tagg.vue")['default']
export const TiptapEditor: typeof import("../components/TiptapEditor.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const TiptapEditorContent: typeof import("../node_modules/@tiptap/vue-3/dist/index")['EditorContent']
export const TiptapFloatingMenu: typeof import("../node_modules/@tiptap/vue-3/dist/index")['FloatingMenu']
export const TiptapBubbleMenu: typeof import("../node_modules/@tiptap/vue-3/dist/index")['BubbleMenu']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCat: typeof import("../components/Cat.vue")['default']
export const LazyCatSingleAdmin: typeof import("../components/CatSingleAdmin.vue")['default']
export const LazyCatSingleOpen: typeof import("../components/CatSingleOpen.vue")['default']
export const LazyCatsAdmin: typeof import("../components/CatsAdmin.vue")['default']
export const LazyCatsOpen: typeof import("../components/CatsOpen.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyMobileHeader: typeof import("../components/MobileHeader.vue")['default']
export const LazyNav: typeof import("../components/Nav.vue")['default']
export const LazyPagination: typeof import("../components/Pagination.vue")['default']
export const LazyProd: typeof import("../components/Prod.vue")['default']
export const LazyProdAdminSingle: typeof import("../components/ProdAdminSingle.vue")['default']
export const LazyProdSingleOpen: typeof import("../components/ProdSingleOpen.vue")['default']
export const LazyProdsAdmin: typeof import("../components/ProdsAdmin.vue")['default']
export const LazyProdsearch: typeof import("../components/Prodsearch.vue")['default']
export const LazyProdsopen: typeof import("../components/Prodsopen.vue")['default']
export const LazySearchbar: typeof import("../components/Searchbar.vue")['default']
export const LazySidebar: typeof import("../components/Sidebar.vue")['default']
export const LazySubCatSingleAdmin: typeof import("../components/SubCatSingleAdmin.vue")['default']
export const LazySubCatSingleOpen: typeof import("../components/SubCatSingleOpen.vue")['default']
export const LazySubcat: typeof import("../components/Subcat.vue")['default']
export const LazySubcatsAdmin: typeof import("../components/SubcatsAdmin.vue")['default']
export const LazySubcatsOpen: typeof import("../components/SubcatsOpen.vue")['default']
export const LazyTagg: typeof import("../components/Tagg.vue")['default']
export const LazyTiptapEditor: typeof import("../components/TiptapEditor.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyTiptapEditorContent: typeof import("../node_modules/@tiptap/vue-3/dist/index")['EditorContent']
export const LazyTiptapFloatingMenu: typeof import("../node_modules/@tiptap/vue-3/dist/index")['FloatingMenu']
export const LazyTiptapBubbleMenu: typeof import("../node_modules/@tiptap/vue-3/dist/index")['BubbleMenu']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
